[build]
cmd = "templ generate && go build -o ./tmp/main main.go"
bin = "tmp/main"
delay = 200                                              # ms
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
include_dir = [".", "ctf", "internal", "ui"]
exclude_dir = ["assets", "tmp", "vendor"]

